#!/bin/bash

# Replace this variable with the path to your site root
# This is where your live site lives
FOLDER=wwwRoot

echo
echo "==== Committing/adding outstanding changes to $FOLDER ===="
echo

# Clearing git env
unset GIT_DIR
unset GIT_WORK_TREE
cd ~/$FOLDER
git commit -am "committing prior to next deployment"

echo
echo "==== Transferring changes to $FOLDER ===="
echo

git pull

echo
echo "==== That's all, folks. ===="
echo
